#Carga de codificación del fondo--------------------------------------------------------------------

message( paste( rep('-', 100 ), collapse = '' ) )

message( '\tLectura la codificación del fondo' )

file_fondo<-paste0(parametros$Data, 'tabla_fondos.xlsx' )

cod_fondo <- read_excel(file_fondo,
                      sheet = 1,
                      col_names = TRUE,
                      col_types = NULL,
                      na = "",
                      skip = 0) %>% clean_names() %>%
  dplyr::select( -entidad , - nombre)

message( paste( rep('-', 100 ), collapse = '' ) )

message( '\tLeyendo estructuras R' )
#Enero de 2021--------------------------------------------------------------------------------------
file_24 <-paste0(parametros$Data,'2021/enero/', 'R24M392731012021.txt' )

col_typ <- c("character",
             "character",
             "character",
             "character", 
             "numeric",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "numeric", 
             "numeric", 
             "character",
             "numeric",
             "character",
             "character",
             "numeric",
             "character")

col_names <- c("id_tipo_afi",
               "cedula",
               "tipo_relacion_afi",
               "actividad_economica",
               "patronimio_afi",
               "fecha_actu_patri",
               "provincia",
               "canton",
               "parroquia",
               "genero",
               "estado_civil",
               "nivel_estudio",
               "profesion",
               "tipo_vivienda",
               "valor_vivienda",
               "tiempo_resid_vivi",
               "relacion_laboral",
               "tiempo_ult_trabajo",
               "fecha_inicio_trabajo_anterior",
               "fecha_salida_trabajo_anterior",
               "cargas_familiares",
               "origen_ingresos")

R24 <- (read.table(file_24,
                   skip = 1,
                   dec = ".",
                   header = TRUE,
                   sep = "\t",
                   #na.strings = "",
                   fill = TRUE,
                   encoding="UTF-8",
                   #nrows = 1000,
                   col.names = col_names,
                   colClasses = col_typ,
                   row.names = NULL)) %>% clean_names()

file_25 <-paste0(parametros$Data,'2021/enero/', 'R25M392731012021.txt' )

col_typ <- c("character",
             "character",
             "character",
             "character", 
             "numeric", 
             "numeric", 
             "numeric", 
             "character",
             "character",
             "character",
             "numeric", 
             "numeric",
             "character",
             "character",
             "character",
             "character",
             "character",
             "numeric", 
             "numeric", 
             "numeric", 
             "character",
             "numeric",
             "numeric",
             "numeric")

col_names <- c("id_tipo_afi",
               "cedula",
               "id_operacion",
               "nut",
               "valor_operacion",
               "tasa_nominal",
               "tasa_efectiva",
               "fecha_concesion",
               "fecha_vencimiento",
               "periocidad_pago",
               "frecuencia_revision",
               "oficina_concecion",
               "garantia",
               "tipo_credito",
               "destino_credito",
               "estado_opeacion",
               "situacion_operacion",
               "total_ingresos_afi",
               "total_egresos_afi",
               "cod_fondo",
               "tipo_garantia",
               "valor_garantia",
               "num_pers_ingres",
               "metros_2")

R25 <- (read.table(file_25,
                   skip = 1,
                   dec = ".",
                   header = TRUE,
                   sep = "\t",
                   fill = TRUE,
                   encoding="UTF-8",
                   #nrows = 10000,
                   col.names = col_names,
                   colClasses = col_typ,
                   row.names = NULL)) %>% clean_names()

sujetos <- R24
conceciones <- R25


#Febrero--------------------------------------------------------------------------------------------

file_24 <-paste0(parametros$Data,'2021/febrero/', 'R24M392728022021.txt' )

col_typ <- c("character",
             "character",
             "character",
             "character", 
             "numeric",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "numeric", 
             "numeric", 
             "character",
             "numeric",
             "character",
             "character",
             "numeric",
             "character")

col_names <- c("id_tipo_afi",
               "cedula",
               "tipo_relacion_afi",
               "actividad_economica",
               "patronimio_afi",
               "fecha_actu_patri",
               "provincia",
               "canton",
               "parroquia",
               "genero",
               "estado_civil",
               "nivel_estudio",
               "profesion",
               "tipo_vivienda",
               "valor_vivienda",
               "tiempo_resid_vivi",
               "relacion_laboral",
               "tiempo_ult_trabajo",
               "fecha_inicio_trabajo_anterior",
               "fecha_salida_trabajo_anterior",
               "cargas_familiares",
               "origen_ingresos")

R24 <- (read.table(file_24,
                   skip = 1,
                   dec = ".",
                   header = TRUE,
                   sep = "\t",
                   #na.strings = "",
                   fill = TRUE,
                   encoding="UTF-8",
                   #nrows = 1000,
                   col.names = col_names,
                   colClasses = col_typ,
                   row.names = NULL)) %>% clean_names()

file_25 <-paste0(parametros$Data,'2021/febrero/', 'R25M392728022021.txt' )

col_typ <- c("character",
             "character",
             "character",
             "character", 
             "numeric", 
             "numeric", 
             "numeric", 
             "character",
             "character",
             "character",
             "numeric", 
             "numeric",
             "character",
             "character",
             "character",
             "character",
             "character",
             "numeric", 
             "numeric", 
             "numeric", 
             "character",
             "numeric",
             "numeric",
             "numeric")

col_names <- c("id_tipo_afi",
               "cedula",
               "id_operacion",
               "nut",
               "valor_operacion",
               "tasa_nominal",
               "tasa_efectiva",
               "fecha_concesion",
               "fecha_vencimiento",
               "periocidad_pago",
               "frecuencia_revision",
               "oficina_concecion",
               "garantia",
               "tipo_credito",
               "destino_credito",
               "estado_opeacion",
               "situacion_operacion",
               "total_ingresos_afi",
               "total_egresos_afi",
               "cod_fondo",
               "tipo_garantia",
               "valor_garantia",
               "num_pers_ingres",
               "metros_2")

R25 <- (read.table(file_25,
                   skip = 1,
                   dec = ".",
                   header = TRUE,
                   sep = "\t",
                   fill = TRUE,
                   encoding="UTF-8",
                   #nrows = 10000,
                   col.names = col_names,
                   colClasses = col_typ,
                   row.names = NULL)) %>% clean_names()

sujetos <- rbind(sujetos, R24)
conceciones <- rbind(conceciones, R25)



#Marzo----------------------------------------------------------------------------------------------

file_24 <-paste0(parametros$Data,'2021/marzo/', 'R24M392731032021.txt' )

col_typ <- c("character",
             "character",
             "character",
             "character", 
             "numeric",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "numeric", 
             "numeric", 
             "character",
             "numeric",
             "character",
             "character",
             "numeric",
             "character")

col_names <- c("id_tipo_afi",
               "cedula",
               "tipo_relacion_afi",
               "actividad_economica",
               "patronimio_afi",
               "fecha_actu_patri",
               "provincia",
               "canton",
               "parroquia",
               "genero",
               "estado_civil",
               "nivel_estudio",
               "profesion",
               "tipo_vivienda",
               "valor_vivienda",
               "tiempo_resid_vivi",
               "relacion_laboral",
               "tiempo_ult_trabajo",
               "fecha_inicio_trabajo_anterior",
               "fecha_salida_trabajo_anterior",
               "cargas_familiares",
               "origen_ingresos")

R24 <- (read.table(file_24,
                   skip = 1,
                   dec = ".",
                   header = TRUE,
                   sep = "\t",
                   #na.strings = "",
                   fill = TRUE,
                   encoding="UTF-8",
                   #nrows = 1000,
                   col.names = col_names,
                   colClasses = col_typ,
                   row.names = NULL)) %>% clean_names()

file_25 <-paste0(parametros$Data,'2021/marzo/', 'R25M392731032021.txt' )

col_typ <- c("character",
             "character",
             "character",
             "character", 
             "numeric", 
             "numeric", 
             "numeric", 
             "character",
             "character",
             "character",
             "numeric", 
             "numeric",
             "character",
             "character",
             "character",
             "character",
             "character",
             "numeric", 
             "numeric", 
             "numeric", 
             "character",
             "numeric",
             "numeric",
             "numeric")

col_names <- c("id_tipo_afi",
               "cedula",
               "id_operacion",
               "nut",
               "valor_operacion",
               "tasa_nominal",
               "tasa_efectiva",
               "fecha_concesion",
               "fecha_vencimiento",
               "periocidad_pago",
               "frecuencia_revision",
               "oficina_concecion",
               "garantia",
               "tipo_credito",
               "destino_credito",
               "estado_opeacion",
               "situacion_operacion",
               "total_ingresos_afi",
               "total_egresos_afi",
               "cod_fondo",
               "tipo_garantia",
               "valor_garantia",
               "num_pers_ingres",
               "metros_2")

R25 <- (read.table(file_25,
                   skip = 1,
                   dec = ".",
                   header = TRUE,
                   sep = "\t",
                   fill = TRUE,
                   encoding="UTF-8",
                   #nrows = 10000,
                   col.names = col_names,
                   colClasses = col_typ,
                   row.names = NULL)) %>% clean_names()

sujetos <- rbind(sujetos, R24)
conceciones <- rbind(conceciones, R25)


#Abril----------------------------------------------------------------------------------------------

file_24 <-paste0(parametros$Data,'2021/abril/', 'R24M392730042021.txt' )

col_typ <- c("character",
             "character",
             "character",
             "character", 
             "numeric",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "numeric", 
             "numeric", 
             "character",
             "numeric",
             "character",
             "character",
             "numeric",
             "character")

col_names <- c("id_tipo_afi",
               "cedula",
               "tipo_relacion_afi",
               "actividad_economica",
               "patronimio_afi",
               "fecha_actu_patri",
               "provincia",
               "canton",
               "parroquia",
               "genero",
               "estado_civil",
               "nivel_estudio",
               "profesion",
               "tipo_vivienda",
               "valor_vivienda",
               "tiempo_resid_vivi",
               "relacion_laboral",
               "tiempo_ult_trabajo",
               "fecha_inicio_trabajo_anterior",
               "fecha_salida_trabajo_anterior",
               "cargas_familiares",
               "origen_ingresos")

R24 <- (read.table(file_24,
                   skip = 1,
                   dec = ".",
                   header = TRUE,
                   sep = "\t",
                   #na.strings = "",
                   fill = TRUE,
                   encoding="UTF-8",
                   #nrows = 1000,
                   col.names = col_names,
                   colClasses = col_typ,
                   row.names = NULL)) %>% clean_names()

file_25 <-paste0(parametros$Data,'2021/abril/', 'R25M392730042021.txt' )

col_typ <- c("character",
             "character",
             "character",
             "character", 
             "numeric", 
             "numeric", 
             "numeric", 
             "character",
             "character",
             "character",
             "numeric", 
             "numeric",
             "character",
             "character",
             "character",
             "character",
             "character",
             "numeric", 
             "numeric", 
             "numeric", 
             "character",
             "numeric",
             "numeric",
             "numeric")

col_names <- c("id_tipo_afi",
               "cedula",
               "id_operacion",
               "nut",
               "valor_operacion",
               "tasa_nominal",
               "tasa_efectiva",
               "fecha_concesion",
               "fecha_vencimiento",
               "periocidad_pago",
               "frecuencia_revision",
               "oficina_concecion",
               "garantia",
               "tipo_credito",
               "destino_credito",
               "estado_opeacion",
               "situacion_operacion",
               "total_ingresos_afi",
               "total_egresos_afi",
               "cod_fondo",
               "tipo_garantia",
               "valor_garantia",
               "num_pers_ingres",
               "metros_2")

R25 <- (read.table(file_25,
                   skip = 1,
                   dec = ".",
                   header = TRUE,
                   sep = "\t",
                   fill = TRUE,
                   encoding="UTF-8",
                   #nrows = 10000,
                   col.names = col_names,
                   colClasses = col_typ,
                   row.names = NULL)) %>% clean_names()

sujetos <- rbind(sujetos, R24)
conceciones <- rbind(conceciones, R25)



#Mayo----------------------------------------------------------------------------------------------

file_24 <-paste0(parametros$Data,'2021/mayo/', 'R24M392731052021.txt' )

col_typ <- c("character",
             "character",
             "character",
             "character", 
             "numeric",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "numeric", 
             "numeric", 
             "character",
             "numeric",
             "character",
             "character",
             "numeric",
             "character")

col_names <- c("id_tipo_afi",
               "cedula",
               "tipo_relacion_afi",
               "actividad_economica",
               "patronimio_afi",
               "fecha_actu_patri",
               "provincia",
               "canton",
               "parroquia",
               "genero",
               "estado_civil",
               "nivel_estudio",
               "profesion",
               "tipo_vivienda",
               "valor_vivienda",
               "tiempo_resid_vivi",
               "relacion_laboral",
               "tiempo_ult_trabajo",
               "fecha_inicio_trabajo_anterior",
               "fecha_salida_trabajo_anterior",
               "cargas_familiares",
               "origen_ingresos")

R24 <- (read.table(file_24,
                   skip = 1,
                   dec = ".",
                   header = TRUE,
                   sep = "\t",
                   #na.strings = "",
                   fill = TRUE,
                   encoding="UTF-8",
                   #nrows = 1000,
                   col.names = col_names,
                   colClasses = col_typ,
                   row.names = NULL)) %>% clean_names()

file_25 <-paste0(parametros$Data,'2021/mayo/', 'R25M392731052021.txt' )

col_typ <- c("character",
             "character",
             "character",
             "character", 
             "numeric", 
             "numeric", 
             "numeric", 
             "character",
             "character",
             "character",
             "numeric", 
             "numeric",
             "character",
             "character",
             "character",
             "character",
             "character",
             "numeric", 
             "numeric", 
             "numeric", 
             "character",
             "numeric",
             "numeric",
             "numeric")

col_names <- c("id_tipo_afi",
               "cedula",
               "id_operacion",
               "nut",
               "valor_operacion",
               "tasa_nominal",
               "tasa_efectiva",
               "fecha_concesion",
               "fecha_vencimiento",
               "periocidad_pago",
               "frecuencia_revision",
               "oficina_concecion",
               "garantia",
               "tipo_credito",
               "destino_credito",
               "estado_opeacion",
               "situacion_operacion",
               "total_ingresos_afi",
               "total_egresos_afi",
               "cod_fondo",
               "tipo_garantia",
               "valor_garantia",
               "num_pers_ingres",
               "metros_2")

R25 <- (read.table(file_25,
                   skip = 1,
                   dec = ".",
                   header = TRUE,
                   sep = "\t",
                   fill = TRUE,
                   encoding="UTF-8",
                   #nrows = 10000,
                   col.names = col_names,
                   colClasses = col_typ,
                   row.names = NULL)) %>% clean_names()

sujetos <- rbind(sujetos, R24)
conceciones <- rbind(conceciones, R25)


#Junio----------------------------------------------------------------------------------------------

file_24 <-paste0(parametros$Data,'2021/junio/', 'R24M392730062021.txt' )

col_typ <- c("character",
             "character",
             "character",
             "character", 
             "numeric",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "numeric", 
             "numeric", 
             "character",
             "numeric",
             "character",
             "character",
             "numeric",
             "character")

col_names <- c("id_tipo_afi",
               "cedula",
               "tipo_relacion_afi",
               "actividad_economica",
               "patronimio_afi",
               "fecha_actu_patri",
               "provincia",
               "canton",
               "parroquia",
               "genero",
               "estado_civil",
               "nivel_estudio",
               "profesion",
               "tipo_vivienda",
               "valor_vivienda",
               "tiempo_resid_vivi",
               "relacion_laboral",
               "tiempo_ult_trabajo",
               "fecha_inicio_trabajo_anterior",
               "fecha_salida_trabajo_anterior",
               "cargas_familiares",
               "origen_ingresos")

R24 <- (read.table(file_24,
                   skip = 1,
                   dec = ".",
                   header = TRUE,
                   sep = "\t",
                   #na.strings = "",
                   fill = TRUE,
                   encoding="UTF-8",
                   #nrows = 1000,
                   col.names = col_names,
                   colClasses = col_typ,
                   row.names = NULL)) %>% clean_names()

file_25 <-paste0(parametros$Data,'2021/junio/', 'R25M392730062021.txt' )

col_typ <- c("character",
             "character",
             "character",
             "character", 
             "numeric", 
             "numeric", 
             "numeric", 
             "character",
             "character",
             "character",
             "numeric", 
             "numeric",
             "character",
             "character",
             "character",
             "character",
             "character",
             "numeric", 
             "numeric", 
             "numeric", 
             "character",
             "numeric",
             "numeric",
             "numeric")

col_names <- c("id_tipo_afi",
               "cedula",
               "id_operacion",
               "nut",
               "valor_operacion",
               "tasa_nominal",
               "tasa_efectiva",
               "fecha_concesion",
               "fecha_vencimiento",
               "periocidad_pago",
               "frecuencia_revision",
               "oficina_concecion",
               "garantia",
               "tipo_credito",
               "destino_credito",
               "estado_opeacion",
               "situacion_operacion",
               "total_ingresos_afi",
               "total_egresos_afi",
               "cod_fondo",
               "tipo_garantia",
               "valor_garantia",
               "num_pers_ingres",
               "metros_2")

R25 <- (read.table(file_25,
                   skip = 1,
                   dec = ".",
                   header = TRUE,
                   sep = "\t",
                   fill = TRUE,
                   encoding="UTF-8",
                   #nrows = 10000,
                   col.names = col_names,
                   colClasses = col_typ,
                   row.names = NULL)) %>% clean_names()

sujetos <- rbind(sujetos, R24)
conceciones <- rbind(conceciones, R25)


#Julio----------------------------------------------------------------------------------------------

file_24 <-paste0(parametros$Data,'2021/julio/', 'R24M392731072021.txt' )

col_typ <- c("character",
             "character",
             "character",
             "character", 
             "numeric",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "numeric", 
             "numeric", 
             "character",
             "numeric",
             "character",
             "character",
             "numeric",
             "character")

col_names <- c("id_tipo_afi",
               "cedula",
               "tipo_relacion_afi",
               "actividad_economica",
               "patronimio_afi",
               "fecha_actu_patri",
               "provincia",
               "canton",
               "parroquia",
               "genero",
               "estado_civil",
               "nivel_estudio",
               "profesion",
               "tipo_vivienda",
               "valor_vivienda",
               "tiempo_resid_vivi",
               "relacion_laboral",
               "tiempo_ult_trabajo",
               "fecha_inicio_trabajo_anterior",
               "fecha_salida_trabajo_anterior",
               "cargas_familiares",
               "origen_ingresos")

R24 <- (read.table(file_24,
                   skip = 1,
                   dec = ".",
                   header = TRUE,
                   sep = "\t",
                   #na.strings = "",
                   fill = TRUE,
                   encoding="UTF-8",
                   #nrows = 1000,
                   col.names = col_names,
                   colClasses = col_typ,
                   row.names = NULL)) %>% clean_names()

file_25 <-paste0(parametros$Data,'2021/julio/', 'R25M392731072021.txt' )

col_typ <- c("character",
             "character",
             "character",
             "character", 
             "numeric", 
             "numeric", 
             "numeric", 
             "character",
             "character",
             "character",
             "numeric", 
             "numeric",
             "character",
             "character",
             "character",
             "character",
             "character",
             "numeric", 
             "numeric", 
             "numeric", 
             "character",
             "numeric",
             "numeric",
             "numeric")

col_names <- c("id_tipo_afi",
               "cedula",
               "id_operacion",
               "nut",
               "valor_operacion",
               "tasa_nominal",
               "tasa_efectiva",
               "fecha_concesion",
               "fecha_vencimiento",
               "periocidad_pago",
               "frecuencia_revision",
               "oficina_concecion",
               "garantia",
               "tipo_credito",
               "destino_credito",
               "estado_opeacion",
               "situacion_operacion",
               "total_ingresos_afi",
               "total_egresos_afi",
               "cod_fondo",
               "tipo_garantia",
               "valor_garantia",
               "num_pers_ingres",
               "metros_2")

R25 <- (read.table(file_25,
                   skip = 1,
                   dec = ".",
                   header = TRUE,
                   sep = "\t",
                   fill = TRUE,
                   encoding="UTF-8",
                   #nrows = 10000,
                   col.names = col_names,
                   colClasses = col_typ,
                   row.names = NULL)) %>% clean_names()

sujetos <- rbind(sujetos, R24)
conceciones <- rbind(conceciones, R25)



#Agosto---------------------------------------------------------------------------------------------

file_24 <-paste0(parametros$Data,'2021/agosto/', 'R24M392731082021.txt' )

col_typ <- c("character",
             "character",
             "character",
             "character", 
             "numeric",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "numeric", 
             "numeric", 
             "character",
             "numeric",
             "character",
             "character",
             "numeric",
             "character")

col_names <- c("id_tipo_afi",
               "cedula",
               "tipo_relacion_afi",
               "actividad_economica",
               "patronimio_afi",
               "fecha_actu_patri",
               "provincia",
               "canton",
               "parroquia",
               "genero",
               "estado_civil",
               "nivel_estudio",
               "profesion",
               "tipo_vivienda",
               "valor_vivienda",
               "tiempo_resid_vivi",
               "relacion_laboral",
               "tiempo_ult_trabajo",
               "fecha_inicio_trabajo_anterior",
               "fecha_salida_trabajo_anterior",
               "cargas_familiares",
               "origen_ingresos")

R24 <- (read.table(file_24,
                   skip = 1,
                   dec = ".",
                   header = TRUE,
                   sep = "\t",
                   #na.strings = "",
                   fill = TRUE,
                   encoding="UTF-8",
                   #nrows = 1000,
                   col.names = col_names,
                   colClasses = col_typ,
                   row.names = NULL)) %>% clean_names()

file_25 <-paste0(parametros$Data,'2021/agosto/', 'R25M392731082021.txt' )

col_typ <- c("character",
             "character",
             "character",
             "character", 
             "numeric", 
             "numeric", 
             "numeric", 
             "character",
             "character",
             "character",
             "numeric", 
             "numeric",
             "character",
             "character",
             "character",
             "character",
             "character",
             "numeric", 
             "numeric", 
             "numeric", 
             "character",
             "numeric",
             "numeric",
             "numeric")

col_names <- c("id_tipo_afi",
               "cedula",
               "id_operacion",
               "nut",
               "valor_operacion",
               "tasa_nominal",
               "tasa_efectiva",
               "fecha_concesion",
               "fecha_vencimiento",
               "periocidad_pago",
               "frecuencia_revision",
               "oficina_concecion",
               "garantia",
               "tipo_credito",
               "destino_credito",
               "estado_opeacion",
               "situacion_operacion",
               "total_ingresos_afi",
               "total_egresos_afi",
               "cod_fondo",
               "tipo_garantia",
               "valor_garantia",
               "num_pers_ingres",
               "metros_2")

R25 <- (read.table(file_25,
                   skip = 1,
                   dec = ".",
                   header = TRUE,
                   sep = "\t",
                   fill = TRUE,
                   encoding="UTF-8",
                   #nrows = 10000,
                   col.names = col_names,
                   colClasses = col_typ,
                   row.names = NULL)) %>% clean_names()

sujetos <- rbind(sujetos, R24)
conceciones <- rbind(conceciones, R25)

#Septiembre---------------------------------------------------------------------------------------------

file_24 <-paste0(parametros$Data,'2021/septiembre/', 'R24M392730092021.txt' )

col_typ <- c("character",
             "character",
             "character",
             "character", 
             "numeric",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "numeric", 
             "numeric", 
             "character",
             "numeric",
             "character",
             "character",
             "numeric",
             "character")

col_names <- c("id_tipo_afi",
               "cedula",
               "tipo_relacion_afi",
               "actividad_economica",
               "patronimio_afi",
               "fecha_actu_patri",
               "provincia",
               "canton",
               "parroquia",
               "genero",
               "estado_civil",
               "nivel_estudio",
               "profesion",
               "tipo_vivienda",
               "valor_vivienda",
               "tiempo_resid_vivi",
               "relacion_laboral",
               "tiempo_ult_trabajo",
               "fecha_inicio_trabajo_anterior",
               "fecha_salida_trabajo_anterior",
               "cargas_familiares",
               "origen_ingresos")

R24 <- (read.table(file_24,
                   skip = 1,
                   dec = ".",
                   header = TRUE,
                   sep = "\t",
                   #na.strings = "",
                   fill = TRUE,
                   encoding="UTF-8",
                   #nrows = 1000,
                   col.names = col_names,
                   colClasses = col_typ,
                   row.names = NULL)) %>% clean_names()

file_25 <-paste0(parametros$Data,'2021/septiembre/', 'R25M392730092021.txt' )

col_typ <- c("character",
             "character",
             "character",
             "character", 
             "numeric", 
             "numeric", 
             "numeric", 
             "character",
             "character",
             "character",
             "numeric", 
             "numeric",
             "character",
             "character",
             "character",
             "character",
             "character",
             "numeric", 
             "numeric", 
             "numeric", 
             "character",
             "numeric",
             "numeric",
             "numeric")

col_names <- c("id_tipo_afi",
               "cedula",
               "id_operacion",
               "nut",
               "valor_operacion",
               "tasa_nominal",
               "tasa_efectiva",
               "fecha_concesion",
               "fecha_vencimiento",
               "periocidad_pago",
               "frecuencia_revision",
               "oficina_concecion",
               "garantia",
               "tipo_credito",
               "destino_credito",
               "estado_opeacion",
               "situacion_operacion",
               "total_ingresos_afi",
               "total_egresos_afi",
               "cod_fondo",
               "tipo_garantia",
               "valor_garantia",
               "num_pers_ingres",
               "metros_2")

R25 <- (read.table(file_25,
                   skip = 1,
                   dec = ".",
                   header = TRUE,
                   sep = "\t",
                   fill = TRUE,
                   encoding="UTF-8",
                   #nrows = 10000,
                   col.names = col_names,
                   colClasses = col_typ,
                   row.names = NULL)) %>% clean_names()

sujetos <- rbind(sujetos, R24)
conceciones <- rbind(conceciones, R25)


#Octubre---------------------------------------------------------------------------------------------

file_24 <-paste0(parametros$Data,'2021/octubre/', 'R24M392731102021.txt' )

col_typ <- c("character",
             "character",
             "character",
             "character", 
             "numeric",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "numeric", 
             "numeric", 
             "character",
             "numeric",
             "character",
             "character",
             "numeric",
             "character")

col_names <- c("id_tipo_afi",
               "cedula",
               "tipo_relacion_afi",
               "actividad_economica",
               "patronimio_afi",
               "fecha_actu_patri",
               "provincia",
               "canton",
               "parroquia",
               "genero",
               "estado_civil",
               "nivel_estudio",
               "profesion",
               "tipo_vivienda",
               "valor_vivienda",
               "tiempo_resid_vivi",
               "relacion_laboral",
               "tiempo_ult_trabajo",
               "fecha_inicio_trabajo_anterior",
               "fecha_salida_trabajo_anterior",
               "cargas_familiares",
               "origen_ingresos")

R24 <- (read.table(file_24,
                   skip = 1,
                   dec = ".",
                   header = TRUE,
                   sep = "\t",
                   #na.strings = "",
                   fill = TRUE,
                   encoding="UTF-8",
                   #nrows = 1000,
                   col.names = col_names,
                   colClasses = col_typ,
                   row.names = NULL)) %>% clean_names()

file_25 <-paste0(parametros$Data,'2021/octubre/', 'R25M392731102021.txt' )

col_typ <- c("character",
             "character",
             "character",
             "character", 
             "numeric", 
             "numeric", 
             "numeric", 
             "character",
             "character",
             "character",
             "numeric", 
             "numeric",
             "character",
             "character",
             "character",
             "character",
             "character",
             "numeric", 
             "numeric", 
             "numeric", 
             "character",
             "numeric",
             "numeric",
             "numeric")

col_names <- c("id_tipo_afi",
               "cedula",
               "id_operacion",
               "nut",
               "valor_operacion",
               "tasa_nominal",
               "tasa_efectiva",
               "fecha_concesion",
               "fecha_vencimiento",
               "periocidad_pago",
               "frecuencia_revision",
               "oficina_concecion",
               "garantia",
               "tipo_credito",
               "destino_credito",
               "estado_opeacion",
               "situacion_operacion",
               "total_ingresos_afi",
               "total_egresos_afi",
               "cod_fondo",
               "tipo_garantia",
               "valor_garantia",
               "num_pers_ingres",
               "metros_2")

R25 <- (read.table(file_25,
                   skip = 1,
                   dec = ".",
                   header = TRUE,
                   sep = "\t",
                   fill = TRUE,
                   encoding="UTF-8",
                   #nrows = 10000,
                   col.names = col_names,
                   colClasses = col_typ,
                   row.names = NULL)) %>% clean_names()

sujetos <- rbind(sujetos, R24)
conceciones <- rbind(conceciones, R25)

#Noviembre---------------------------------------------------------------------------------------------

file_24 <-paste0(parametros$Data,'2021/noviembre/', 'R24M392730112021.txt' )

col_typ <- c("character",
             "character",
             "character",
             "character", 
             "numeric",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "numeric", 
             "numeric", 
             "character",
             "numeric",
             "character",
             "character",
             "numeric",
             "character")

col_names <- c("id_tipo_afi",
               "cedula",
               "tipo_relacion_afi",
               "actividad_economica",
               "patronimio_afi",
               "fecha_actu_patri",
               "provincia",
               "canton",
               "parroquia",
               "genero",
               "estado_civil",
               "nivel_estudio",
               "profesion",
               "tipo_vivienda",
               "valor_vivienda",
               "tiempo_resid_vivi",
               "relacion_laboral",
               "tiempo_ult_trabajo",
               "fecha_inicio_trabajo_anterior",
               "fecha_salida_trabajo_anterior",
               "cargas_familiares",
               "origen_ingresos")

R24 <- (read.table(file_24,
                   skip = 1,
                   dec = ".",
                   header = TRUE,
                   sep = "\t",
                   #na.strings = "",
                   fill = TRUE,
                   encoding="UTF-8",
                   #nrows = 1000,
                   col.names = col_names,
                   colClasses = col_typ,
                   row.names = NULL)) %>% clean_names()

file_25 <-paste0(parametros$Data,'2021/noviembre/', 'R25M392730112021.txt' )

col_typ <- c("character",
             "character",
             "character",
             "character", 
             "numeric", 
             "numeric", 
             "numeric", 
             "character",
             "character",
             "character",
             "numeric", 
             "numeric",
             "character",
             "character",
             "character",
             "character",
             "character",
             "numeric", 
             "numeric", 
             "numeric", 
             "character",
             "numeric",
             "numeric",
             "numeric")

col_names <- c("id_tipo_afi",
               "cedula",
               "id_operacion",
               "nut",
               "valor_operacion",
               "tasa_nominal",
               "tasa_efectiva",
               "fecha_concesion",
               "fecha_vencimiento",
               "periocidad_pago",
               "frecuencia_revision",
               "oficina_concecion",
               "garantia",
               "tipo_credito",
               "destino_credito",
               "estado_opeacion",
               "situacion_operacion",
               "total_ingresos_afi",
               "total_egresos_afi",
               "cod_fondo",
               "tipo_garantia",
               "valor_garantia",
               "num_pers_ingres",
               "metros_2")

R25 <- (read.table(file_25,
                   skip = 1,
                   dec = ".",
                   header = TRUE,
                   sep = "\t",
                   fill = TRUE,
                   encoding="UTF-8",
                   #nrows = 10000,
                   col.names = col_names,
                   colClasses = col_typ,
                   row.names = NULL)) %>% clean_names()

sujetos <- rbind(sujetos, R24)
conceciones <- rbind(conceciones, R25)

#Diciembre---------------------------------------------------------------------------------------------

file_24 <-paste0(parametros$Data,'2021/diciembre/', 'R24M392731122021.txt' )

col_typ <- c("character",
             "character",
             "character",
             "character", 
             "numeric",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "numeric", 
             "numeric", 
             "character",
             "numeric",
             "character",
             "character",
             "numeric",
             "character")

col_names <- c("id_tipo_afi",
               "cedula",
               "tipo_relacion_afi",
               "actividad_economica",
               "patronimio_afi",
               "fecha_actu_patri",
               "provincia",
               "canton",
               "parroquia",
               "genero",
               "estado_civil",
               "nivel_estudio",
               "profesion",
               "tipo_vivienda",
               "valor_vivienda",
               "tiempo_resid_vivi",
               "relacion_laboral",
               "tiempo_ult_trabajo",
               "fecha_inicio_trabajo_anterior",
               "fecha_salida_trabajo_anterior",
               "cargas_familiares",
               "origen_ingresos")

R24 <- (read.table(file_24,
                   skip = 1,
                   dec = ".",
                   header = TRUE,
                   sep = "\t",
                   #na.strings = "",
                   fill = TRUE,
                   encoding="UTF-8",
                   #nrows = 1000,
                   col.names = col_names,
                   colClasses = col_typ,
                   row.names = NULL)) %>% clean_names()

file_25 <-paste0(parametros$Data,'2021/diciembre/', 'R25M392731122021.txt' )

col_typ <- c("character",
             "character",
             "character",
             "character", 
             "numeric", 
             "numeric", 
             "numeric", 
             "character",
             "character",
             "character",
             "numeric", 
             "numeric",
             "character",
             "character",
             "character",
             "character",
             "character",
             "numeric", 
             "numeric", 
             "numeric", 
             "character",
             "numeric",
             "numeric",
             "numeric")

col_names <- c("id_tipo_afi",
               "cedula",
               "id_operacion",
               "nut",
               "valor_operacion",
               "tasa_nominal",
               "tasa_efectiva",
               "fecha_concesion",
               "fecha_vencimiento",
               "periocidad_pago",
               "frecuencia_revision",
               "oficina_concecion",
               "garantia",
               "tipo_credito",
               "destino_credito",
               "estado_opeacion",
               "situacion_operacion",
               "total_ingresos_afi",
               "total_egresos_afi",
               "cod_fondo",
               "tipo_garantia",
               "valor_garantia",
               "num_pers_ingres",
               "metros_2")

R25 <- (read.table(file_25,
                   skip = 1,
                   dec = ".",
                   header = TRUE,
                   sep = "\t",
                   fill = TRUE,
                   encoding="UTF-8",
                   #nrows = 10000,
                   col.names = col_names,
                   colClasses = col_typ,
                   row.names = NULL)) %>% clean_names()

sujetos_2021 <- rbind(sujetos, R24)
conceciones_2021 <- rbind(conceciones, R25)



#Enero de 2022--------------------------------------------------------------------------------------
file_24 <-paste0(parametros$Data,'enero/', 'R24M392731012022.txt' )

col_typ <- c("character",
             "character",
             "character",
             "character", 
             "numeric",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "numeric", 
             "numeric", 
             "character",
             "numeric",
             "character",
             "character",
             "numeric",
             "character")

col_names <- c("id_tipo_afi",
               "cedula",
               "tipo_relacion_afi",
               "actividad_economica",
               "patronimio_afi",
               "fecha_actu_patri",
               "provincia",
               "canton",
               "parroquia",
               "genero",
               "estado_civil",
               "nivel_estudio",
               "profesion",
               "tipo_vivienda",
               "valor_vivienda",
               "tiempo_resid_vivi",
               "relacion_laboral",
               "tiempo_ult_trabajo",
               "fecha_inicio_trabajo_anterior",
               "fecha_salida_trabajo_anterior",
               "cargas_familiares",
               "origen_ingresos")

R24 <- (read.table(file_24,
                   skip = 1,
                   dec = ".",
                   header = TRUE,
                   sep = "\t",
                   #na.strings = "",
                   fill = TRUE,
                   encoding="UTF-8",
                   #nrows = 1000,
                   col.names = col_names,
                   colClasses = col_typ,
                   row.names = NULL)) %>% clean_names()

file_25 <-paste0(parametros$Data,'enero/', 'R25M392731012022.txt' )

col_typ <- c("character",
             "character",
             "character",
             "character", 
             "numeric", 
             "numeric", 
             "numeric", 
             "character",
             "character",
             "character",
             "numeric", 
             "numeric",
             "character",
             "character",
             "character",
             "character",
             "character",
             "numeric", 
             "numeric", 
             "numeric", 
             "character",
             "numeric",
             "numeric",
             "numeric")

col_names <- c("id_tipo_afi",
               "cedula",
               "id_operacion",
               "nut",
               "valor_operacion",
               "tasa_nominal",
               "tasa_efectiva",
               "fecha_concesion",
               "fecha_vencimiento",
               "periocidad_pago",
               "frecuencia_revision",
               "oficina_concecion",
               "garantia",
               "tipo_credito",
               "destino_credito",
               "estado_opeacion",
               "situacion_operacion",
               "total_ingresos_afi",
               "total_egresos_afi",
               "cod_fondo",
               "tipo_garantia",
               "valor_garantia",
               "num_pers_ingres",
               "metros_2")

R25 <- (read.table(file_25,
                   skip = 1,
                   dec = ".",
                   header = TRUE,
                   sep = "\t",
                   fill = TRUE,
                   encoding="UTF-8",
                   #nrows = 10000,
                   col.names = col_names,
                   colClasses = col_typ,
                   row.names = NULL)) %>% clean_names()

sujetos <- R24
conceciones <- R25


#Febrero--------------------------------------------------------------------------------------------

file_24 <-paste0(parametros$Data,'febrero/', 'R24M392728022022.txt' )

col_typ <- c("character",
             "character",
             "character",
             "character", 
             "numeric",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "numeric", 
             "numeric", 
             "character",
             "numeric",
             "character",
             "character",
             "numeric",
             "character")

col_names <- c("id_tipo_afi",
               "cedula",
               "tipo_relacion_afi",
               "actividad_economica",
               "patronimio_afi",
               "fecha_actu_patri",
               "provincia",
               "canton",
               "parroquia",
               "genero",
               "estado_civil",
               "nivel_estudio",
               "profesion",
               "tipo_vivienda",
               "valor_vivienda",
               "tiempo_resid_vivi",
               "relacion_laboral",
               "tiempo_ult_trabajo",
               "fecha_inicio_trabajo_anterior",
               "fecha_salida_trabajo_anterior",
               "cargas_familiares",
               "origen_ingresos")

R24 <- (read.table(file_24,
                   skip = 1,
                   dec = ".",
                   header = TRUE,
                   sep = "\t",
                   #na.strings = "",
                   fill = TRUE,
                   encoding="UTF-8",
                   #nrows = 1000,
                   col.names = col_names,
                   colClasses = col_typ,
                   row.names = NULL)) %>% clean_names()

file_25 <-paste0(parametros$Data,'febrero/', 'R25M392728022022.txt' )

col_typ <- c("character",
             "character",
             "character",
             "character", 
             "numeric", 
             "numeric", 
             "numeric", 
             "character",
             "character",
             "character",
             "numeric", 
             "numeric",
             "character",
             "character",
             "character",
             "character",
             "character",
             "numeric", 
             "numeric", 
             "numeric", 
             "character",
             "numeric",
             "numeric",
             "numeric")

col_names <- c("id_tipo_afi",
               "cedula",
               "id_operacion",
               "nut",
               "valor_operacion",
               "tasa_nominal",
               "tasa_efectiva",
               "fecha_concesion",
               "fecha_vencimiento",
               "periocidad_pago",
               "frecuencia_revision",
               "oficina_concecion",
               "garantia",
               "tipo_credito",
               "destino_credito",
               "estado_opeacion",
               "situacion_operacion",
               "total_ingresos_afi",
               "total_egresos_afi",
               "cod_fondo",
               "tipo_garantia",
               "valor_garantia",
               "num_pers_ingres",
               "metros_2")

R25 <- (read.table(file_25,
                   skip = 1,
                   dec = ".",
                   header = TRUE,
                   sep = "\t",
                   fill = TRUE,
                   encoding="UTF-8",
                   #nrows = 10000,
                   col.names = col_names,
                   colClasses = col_typ,
                   row.names = NULL)) %>% clean_names()

sujetos <- rbind(sujetos, R24)
conceciones <- rbind(conceciones, R25)



#Marzo----------------------------------------------------------------------------------------------

file_24 <-paste0(parametros$Data,'marzo/', 'R24M392731032022.txt' )

col_typ <- c("character",
             "character",
             "character",
             "character", 
             "numeric",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "numeric", 
             "numeric", 
             "character",
             "numeric",
             "character",
             "character",
             "numeric",
             "character")

col_names <- c("id_tipo_afi",
               "cedula",
               "tipo_relacion_afi",
               "actividad_economica",
               "patronimio_afi",
               "fecha_actu_patri",
               "provincia",
               "canton",
               "parroquia",
               "genero",
               "estado_civil",
               "nivel_estudio",
               "profesion",
               "tipo_vivienda",
               "valor_vivienda",
               "tiempo_resid_vivi",
               "relacion_laboral",
               "tiempo_ult_trabajo",
               "fecha_inicio_trabajo_anterior",
               "fecha_salida_trabajo_anterior",
               "cargas_familiares",
               "origen_ingresos")

R24 <- (read.table(file_24,
                   skip = 1,
                   dec = ".",
                   header = TRUE,
                   sep = "\t",
                   #na.strings = "",
                   fill = TRUE,
                   encoding="UTF-8",
                   #nrows = 1000,
                   col.names = col_names,
                   colClasses = col_typ,
                   row.names = NULL)) %>% clean_names()

file_25 <-paste0(parametros$Data,'marzo/', 'R25M392731032022.txt' )

col_typ <- c("character",
             "character",
             "character",
             "character", 
             "numeric", 
             "numeric", 
             "numeric", 
             "character",
             "character",
             "character",
             "numeric", 
             "numeric",
             "character",
             "character",
             "character",
             "character",
             "character",
             "numeric", 
             "numeric", 
             "numeric", 
             "character",
             "numeric",
             "numeric",
             "numeric")

col_names <- c("id_tipo_afi",
               "cedula",
               "id_operacion",
               "nut",
               "valor_operacion",
               "tasa_nominal",
               "tasa_efectiva",
               "fecha_concesion",
               "fecha_vencimiento",
               "periocidad_pago",
               "frecuencia_revision",
               "oficina_concecion",
               "garantia",
               "tipo_credito",
               "destino_credito",
               "estado_opeacion",
               "situacion_operacion",
               "total_ingresos_afi",
               "total_egresos_afi",
               "cod_fondo",
               "tipo_garantia",
               "valor_garantia",
               "num_pers_ingres",
               "metros_2")

R25 <- (read.table(file_25,
                   skip = 1,
                   dec = ".",
                   header = TRUE,
                   sep = "\t",
                   fill = TRUE,
                   encoding="UTF-8",
                   #nrows = 10000,
                   col.names = col_names,
                   colClasses = col_typ,
                   row.names = NULL)) %>% clean_names()

sujetos <- rbind(sujetos, R24)
conceciones <- rbind(conceciones, R25)


#Abril----------------------------------------------------------------------------------------------

file_24 <-paste0(parametros$Data,'abril/', 'R24M392730042022.txt' )

col_typ <- c("character",
             "character",
             "character",
             "character", 
             "numeric",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "numeric", 
             "numeric", 
             "character",
             "numeric",
             "character",
             "character",
             "numeric",
             "character")

col_names <- c("id_tipo_afi",
               "cedula",
               "tipo_relacion_afi",
               "actividad_economica",
               "patronimio_afi",
               "fecha_actu_patri",
               "provincia",
               "canton",
               "parroquia",
               "genero",
               "estado_civil",
               "nivel_estudio",
               "profesion",
               "tipo_vivienda",
               "valor_vivienda",
               "tiempo_resid_vivi",
               "relacion_laboral",
               "tiempo_ult_trabajo",
               "fecha_inicio_trabajo_anterior",
               "fecha_salida_trabajo_anterior",
               "cargas_familiares",
               "origen_ingresos")

R24 <- (read.table(file_24,
                   skip = 1,
                   dec = ".",
                   header = TRUE,
                   sep = "\t",
                   #na.strings = "",
                   fill = TRUE,
                   encoding="UTF-8",
                   #nrows = 1000,
                   col.names = col_names,
                   colClasses = col_typ,
                   row.names = NULL)) %>% clean_names()

file_25 <-paste0(parametros$Data,'abril/', 'R25M392730042022.txt' )

col_typ <- c("character",
             "character",
             "character",
             "character", 
             "numeric", 
             "numeric", 
             "numeric", 
             "character",
             "character",
             "character",
             "numeric", 
             "numeric",
             "character",
             "character",
             "character",
             "character",
             "character",
             "numeric", 
             "numeric", 
             "numeric", 
             "character",
             "numeric",
             "numeric",
             "numeric")

col_names <- c("id_tipo_afi",
               "cedula",
               "id_operacion",
               "nut",
               "valor_operacion",
               "tasa_nominal",
               "tasa_efectiva",
               "fecha_concesion",
               "fecha_vencimiento",
               "periocidad_pago",
               "frecuencia_revision",
               "oficina_concecion",
               "garantia",
               "tipo_credito",
               "destino_credito",
               "estado_opeacion",
               "situacion_operacion",
               "total_ingresos_afi",
               "total_egresos_afi",
               "cod_fondo",
               "tipo_garantia",
               "valor_garantia",
               "num_pers_ingres",
               "metros_2")

R25 <- (read.table(file_25,
                   skip = 1,
                   dec = ".",
                   header = TRUE,
                   sep = "\t",
                   fill = TRUE,
                   encoding="UTF-8",
                   #nrows = 10000,
                   col.names = col_names,
                   colClasses = col_typ,
                   row.names = NULL)) %>% clean_names()

sujetos <- rbind(sujetos, R24)
conceciones <- rbind(conceciones, R25)



#Mayo----------------------------------------------------------------------------------------------

file_24 <-paste0(parametros$Data,'mayo/', 'R24M392731052022.txt' )

col_typ <- c("character",
             "character",
             "character",
             "character", 
             "numeric",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "numeric", 
             "numeric", 
             "character",
             "numeric",
             "character",
             "character",
             "numeric",
             "character")

col_names <- c("id_tipo_afi",
               "cedula",
               "tipo_relacion_afi",
               "actividad_economica",
               "patronimio_afi",
               "fecha_actu_patri",
               "provincia",
               "canton",
               "parroquia",
               "genero",
               "estado_civil",
               "nivel_estudio",
               "profesion",
               "tipo_vivienda",
               "valor_vivienda",
               "tiempo_resid_vivi",
               "relacion_laboral",
               "tiempo_ult_trabajo",
               "fecha_inicio_trabajo_anterior",
               "fecha_salida_trabajo_anterior",
               "cargas_familiares",
               "origen_ingresos")

R24 <- (read.table(file_24,
                   skip = 1,
                   dec = ".",
                   header = TRUE,
                   sep = "\t",
                   #na.strings = "",
                   fill = TRUE,
                   encoding="UTF-8",
                   #nrows = 1000,
                   col.names = col_names,
                   colClasses = col_typ,
                   row.names = NULL)) %>% clean_names()

file_25 <-paste0(parametros$Data,'mayo/', 'R25M392731052022.txt' )

col_typ <- c("character",
             "character",
             "character",
             "character", 
             "numeric", 
             "numeric", 
             "numeric", 
             "character",
             "character",
             "character",
             "numeric", 
             "numeric",
             "character",
             "character",
             "character",
             "character",
             "character",
             "numeric", 
             "numeric", 
             "numeric", 
             "character",
             "numeric",
             "numeric",
             "numeric")

col_names <- c("id_tipo_afi",
               "cedula",
               "id_operacion",
               "nut",
               "valor_operacion",
               "tasa_nominal",
               "tasa_efectiva",
               "fecha_concesion",
               "fecha_vencimiento",
               "periocidad_pago",
               "frecuencia_revision",
               "oficina_concecion",
               "garantia",
               "tipo_credito",
               "destino_credito",
               "estado_opeacion",
               "situacion_operacion",
               "total_ingresos_afi",
               "total_egresos_afi",
               "cod_fondo",
               "tipo_garantia",
               "valor_garantia",
               "num_pers_ingres",
               "metros_2")

R25 <- (read.table(file_25,
                   skip = 1,
                   dec = ".",
                   header = TRUE,
                   sep = "\t",
                   fill = TRUE,
                   encoding="UTF-8",
                   #nrows = 10000,
                   col.names = col_names,
                   colClasses = col_typ,
                   row.names = NULL)) %>% clean_names()

sujetos <- rbind(sujetos, R24)
conceciones <- rbind(conceciones, R25)


#Junio----------------------------------------------------------------------------------------------

file_24 <-paste0(parametros$Data,'junio/', 'R24M392730062022.txt' )

col_typ <- c("character",
             "character",
             "character",
             "character", 
             "numeric",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "numeric", 
             "numeric", 
             "character",
             "numeric",
             "character",
             "character",
             "numeric",
             "character")

col_names <- c("id_tipo_afi",
               "cedula",
               "tipo_relacion_afi",
               "actividad_economica",
               "patronimio_afi",
               "fecha_actu_patri",
               "provincia",
               "canton",
               "parroquia",
               "genero",
               "estado_civil",
               "nivel_estudio",
               "profesion",
               "tipo_vivienda",
               "valor_vivienda",
               "tiempo_resid_vivi",
               "relacion_laboral",
               "tiempo_ult_trabajo",
               "fecha_inicio_trabajo_anterior",
               "fecha_salida_trabajo_anterior",
               "cargas_familiares",
               "origen_ingresos")

R24 <- (read.table(file_24,
                   skip = 1,
                   dec = ".",
                   header = TRUE,
                   sep = "\t",
                   #na.strings = "",
                   fill = TRUE,
                   encoding="UTF-8",
                   #nrows = 1000,
                   col.names = col_names,
                   colClasses = col_typ,
                   row.names = NULL)) %>% clean_names()

file_25 <-paste0(parametros$Data,'junio/', 'R25M392730062022.txt' )

col_typ <- c("character",
             "character",
             "character",
             "character", 
             "numeric", 
             "numeric", 
             "numeric", 
             "character",
             "character",
             "character",
             "numeric", 
             "numeric",
             "character",
             "character",
             "character",
             "character",
             "character",
             "numeric", 
             "numeric", 
             "numeric", 
             "character",
             "numeric",
             "numeric",
             "numeric")

col_names <- c("id_tipo_afi",
               "cedula",
               "id_operacion",
               "nut",
               "valor_operacion",
               "tasa_nominal",
               "tasa_efectiva",
               "fecha_concesion",
               "fecha_vencimiento",
               "periocidad_pago",
               "frecuencia_revision",
               "oficina_concecion",
               "garantia",
               "tipo_credito",
               "destino_credito",
               "estado_opeacion",
               "situacion_operacion",
               "total_ingresos_afi",
               "total_egresos_afi",
               "cod_fondo",
               "tipo_garantia",
               "valor_garantia",
               "num_pers_ingres",
               "metros_2")

R25 <- (read.table(file_25,
                   skip = 1,
                   dec = ".",
                   header = TRUE,
                   sep = "\t",
                   fill = TRUE,
                   encoding="UTF-8",
                   #nrows = 10000,
                   col.names = col_names,
                   colClasses = col_typ,
                   row.names = NULL)) %>% clean_names()

sujetos <- rbind(sujetos, R24)
conceciones <- rbind(conceciones, R25)


#Julio----------------------------------------------------------------------------------------------

file_24 <-paste0(parametros$Data,'julio/', 'R24M392731072022.txt' )

col_typ <- c("character",
             "character",
             "character",
             "character", 
             "numeric",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "numeric", 
             "numeric", 
             "character",
             "numeric",
             "character",
             "character",
             "numeric",
             "character")

col_names <- c("id_tipo_afi",
               "cedula",
               "tipo_relacion_afi",
               "actividad_economica",
               "patronimio_afi",
               "fecha_actu_patri",
               "provincia",
               "canton",
               "parroquia",
               "genero",
               "estado_civil",
               "nivel_estudio",
               "profesion",
               "tipo_vivienda",
               "valor_vivienda",
               "tiempo_resid_vivi",
               "relacion_laboral",
               "tiempo_ult_trabajo",
               "fecha_inicio_trabajo_anterior",
               "fecha_salida_trabajo_anterior",
               "cargas_familiares",
               "origen_ingresos")

R24 <- (read.table(file_24,
                   skip = 1,
                   dec = ".",
                   header = TRUE,
                   sep = "\t",
                   #na.strings = "",
                   fill = TRUE,
                   encoding="UTF-8",
                   #nrows = 1000,
                   col.names = col_names,
                   colClasses = col_typ,
                   row.names = NULL)) %>% clean_names()

file_25 <-paste0(parametros$Data,'julio/', 'R25M392731072022.txt' )

col_typ <- c("character",
             "character",
             "character",
             "character", 
             "numeric", 
             "numeric", 
             "numeric", 
             "character",
             "character",
             "character",
             "numeric", 
             "numeric",
             "character",
             "character",
             "character",
             "character",
             "character",
             "numeric", 
             "numeric", 
             "numeric", 
             "character",
             "numeric",
             "numeric",
             "numeric")

col_names <- c("id_tipo_afi",
               "cedula",
               "id_operacion",
               "nut",
               "valor_operacion",
               "tasa_nominal",
               "tasa_efectiva",
               "fecha_concesion",
               "fecha_vencimiento",
               "periocidad_pago",
               "frecuencia_revision",
               "oficina_concecion",
               "garantia",
               "tipo_credito",
               "destino_credito",
               "estado_opeacion",
               "situacion_operacion",
               "total_ingresos_afi",
               "total_egresos_afi",
               "cod_fondo",
               "tipo_garantia",
               "valor_garantia",
               "num_pers_ingres",
               "metros_2")

R25 <- (read.table(file_25,
                   skip = 1,
                   dec = ".",
                   header = TRUE,
                   sep = "\t",
                   fill = TRUE,
                   encoding="UTF-8",
                   #nrows = 10000,
                   col.names = col_names,
                   colClasses = col_typ,
                   row.names = NULL)) %>% clean_names()

sujetos <- rbind(sujetos, R24)
conceciones <- rbind(conceciones, R25)



#Agosto---------------------------------------------------------------------------------------------

file_24 <-paste0(parametros$Data,'agosto/', 'R24M392731082022.txt' )

col_typ <- c("character",
             "character",
             "character",
             "character", 
             "numeric",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "character",
             "numeric", 
             "numeric", 
             "character",
             "numeric",
             "character",
             "character",
             "numeric",
             "character")

col_names <- c("id_tipo_afi",
               "cedula",
               "tipo_relacion_afi",
               "actividad_economica",
               "patronimio_afi",
               "fecha_actu_patri",
               "provincia",
               "canton",
               "parroquia",
               "genero",
               "estado_civil",
               "nivel_estudio",
               "profesion",
               "tipo_vivienda",
               "valor_vivienda",
               "tiempo_resid_vivi",
               "relacion_laboral",
               "tiempo_ult_trabajo",
               "fecha_inicio_trabajo_anterior",
               "fecha_salida_trabajo_anterior",
               "cargas_familiares",
               "origen_ingresos")

R24 <- (read.table(file_24,
                   skip = 1,
                   dec = ".",
                   header = TRUE,
                   sep = "\t",
                   #na.strings = "",
                   fill = TRUE,
                   encoding="UTF-8",
                   #nrows = 1000,
                   col.names = col_names,
                   colClasses = col_typ,
                   row.names = NULL)) %>% clean_names()

file_25 <-paste0(parametros$Data,'agosto/', 'R25M392731082022.txt' )

col_typ <- c("character",
             "character",
             "character",
             "character", 
             "numeric", 
             "numeric", 
             "numeric", 
             "character",
             "character",
             "character",
             "numeric", 
             "numeric",
             "character",
             "character",
             "character",
             "character",
             "character",
             "numeric", 
             "numeric", 
             "numeric", 
             "character",
             "numeric",
             "numeric",
             "numeric")

col_names <- c("id_tipo_afi",
               "cedula",
               "id_operacion",
               "nut",
               "valor_operacion",
               "tasa_nominal",
               "tasa_efectiva",
               "fecha_concesion",
               "fecha_vencimiento",
               "periocidad_pago",
               "frecuencia_revision",
               "oficina_concecion",
               "garantia",
               "tipo_credito",
               "destino_credito",
               "estado_opeacion",
               "situacion_operacion",
               "total_ingresos_afi",
               "total_egresos_afi",
               "cod_fondo",
               "tipo_garantia",
               "valor_garantia",
               "num_pers_ingres",
               "metros_2")

R25 <- (read.table(file_25,
                   skip = 1,
                   dec = ".",
                   header = TRUE,
                   sep = "\t",
                   fill = TRUE,
                   encoding="UTF-8",
                   #nrows = 10000,
                   col.names = col_names,
                   colClasses = col_typ,
                   row.names = NULL)) %>% clean_names()

sujetos <- rbind(sujetos, R24)
conceciones <- rbind(conceciones, R25)


#Transformación a fechas-----------------------------------------------------------------------------

sujetos <- sujetos %>%
  mutate( fecha_actu_patri = as.Date( fecha_actu_patri, "%d/%m/%Y") ) %>%
  mutate( fecha_inicio_trabajo_anterior = as.Date( fecha_inicio_trabajo_anterior, "%d/%m/%Y") ) %>%
  mutate( fecha_salida_trabajo_anterior  = as.Date( fecha_salida_trabajo_anterior , "%d/%m/%Y") )

sujetos_2021 <- sujetos_2021 %>%
  mutate( fecha_actu_patri = as.Date( fecha_actu_patri, "%d/%m/%Y") ) %>%
  mutate( fecha_inicio_trabajo_anterior = as.Date( fecha_inicio_trabajo_anterior, "%d/%m/%Y") ) %>%
  mutate( fecha_salida_trabajo_anterior  = as.Date( fecha_salida_trabajo_anterior , "%d/%m/%Y") )

conceciones <- conceciones %>%
  mutate( fecha_concesion = as.Date( fecha_concesion , "%d/%m/%Y"),
          fecha_vencimiento  = as.Date( fecha_vencimiento , "%d/%m/%Y") ) %>%
  left_join(.,cod_fondo, by="cod_fondo") %>%
mutate( plazo = (age_calc(dob = fecha_concesion, enddate = fecha_vencimiento, units = "months") ) )

conceciones_2021 <- conceciones_2021 %>%
  mutate( fecha_concesion = as.Date( fecha_concesion , "%d/%m/%Y"),
          fecha_vencimiento  = as.Date( fecha_vencimiento , "%d/%m/%Y") ) %>%
  left_join(.,cod_fondo, by="cod_fondo") %>%
  mutate( plazo = age_calc(dob = fecha_concesion, enddate = fecha_vencimiento, units = "months") ) 

#Se guarda la información en extensión .RData-------------------------------------------------------
save( sujetos,
      sujetos_2021,
      conceciones,
      conceciones_2021,
      file = paste0( parametros$RData, 'BIESS_concesiones_2021_2022.RData' ) )

#Limpiar la Ram-------------------------------------------------------------------------------------
message( paste( rep('-', 100 ), collapse = '' ) )
rm( list = ls()[ !( ls() %in% c( 'parametros' ) ) ] )
gc()